// strings.js — локализация

export const strings = {
    en: {
        recentVideosTitle: "Recent Videos",
        modalTitle: "Welcome!",
        modalDescription: "Swipe right on a link card to subscribe, swipe left on YouTube links to open the latest video or a live stream.",
        gotItButton: "Got it!",
        themeLight: "Light Theme",
        themeDark: "Dark Theme",
        watchOnTwitch: "Watch on Twitch",
        totalFollowers: "Total Followers: ",
        minecraftTitle: "My Minecraft Skin",
        downloadSkin: "Download Skin",
        loading: "Loading...",
        supportButton: "Support Me",
        offlineMessage: "You are offline. Data might be outdated.",
        devPageTitle: "Developer Info",
        devLastUpdatedLabel: "Last Data Update:",
        devDataJsonContentLabel: "data.json Content:",
        devDebugInfoContentLabel: "API Debug Info:",
        backToMainText: "Back to Main Site",
        openLinkButton: "Open Link",
        closeButton: "Close",

        profileName: "BezzubickMCPlay",
        profileDescription: "Minecraft adventures | Streams | Creativity",
        avatarAlt: "BezzubickMCPlay profile avatar",
        previewAvatarAlt: "Link preview avatar",
        twitchStreamAlsoLive: "Stream also live on Twitch!",
        localIconExample: "Custom Local Icon Example",
        skinViewerLoadError: "3D Skin Viewer failed to load. Please check your internet connection and browser extensions.",

        youtubeChannelLabel: "YouTube Channel",
        telegramChannelLabel: "Telegram Channel",
        instagramProfileLabel: "Instagram Profile",
        xTwitterProfileLabel: "X (Twitter) Profile",
        twitchChannelLabel: "Twitch Channel",
        tiktokProfileLabel: "TikTok Profile",
        vkGroupLabel: "VK Group",
        vkPersonalPageLabel: "VK Personal Page",
        myPortfolioLabel: "My Portfolio",
        hiddenLinkExample: "Hidden Link Example"
    },
    ru: {
        recentVideosTitle: "Последние видео",
        modalTitle: "Добро пожаловать!",
        modalDescription: "Проведите вправо по карточке ссылки, чтобы подписаться. Проведите влево по YouTube-ссылкам, чтобы открыть последнее видео или прямой эфир.",
        gotItButton: "Понятно!",
        themeLight: "Светлая тема",
        themeDark: "Тёмная тема",
        watchOnTwitch: "Смотреть на Twitch",
        totalFollowers: "Всего подписчиков: ",
        minecraftTitle: "Мой скин Minecraft",
        downloadSkin: "Скачать скин",
        loading: "Загрузка...",
        supportButton: "Поддержать меня",
        offlineMessage: "Вы не в сети. Данные могут быть устаревшими.",
        devPageTitle: "Информация для разработчиков",
        devLastUpdatedLabel: "Последнее обновление данных:",
        devDataJsonContentLabel: "Содержимое data.json:",
        devDebugInfoContentLabel: "Отладочная информация API:",
        backToMainText: "Назад к сайту",
        openLinkButton: "Открыть ссылку",
        closeButton: "Закрыть",

        profileName: "BezzubickMCPlay",
        profileDescription: "Приключения в Minecraft | Стримы | Творчество",
        avatarAlt: "Аватар профиля BezzubickMCPlay",
        previewAvatarAlt: "Аватар предпросмотра ссылки",
        twitchStreamAlsoLive: "Стрим также идёт на Twitch!",
        localIconExample: "Пример локальной иконки",
        skinViewerLoadError: "3D-просмотрщик скина не загрузился. Проверьте подключение и расширения браузера.",

        youtubeChannelLabel: "YouTube Канал",
        telegramChannelLabel: "Telegram Канал",
        instagramProfileLabel: "Профиль Instagram",
        xTwitterProfileLabel: "Профиль X (Twitter)",
        twitchChannelLabel: "Twitch Канал",
        tiktokProfileLabel: "Профиль TikTok",
        vkGroupLabel: "Группа VK",
        vkPersonalPageLabel: "Личная страница VK",
        myPortfolioLabel: "Моё портфолио",
        hiddenLinkExample: "Пример скрытой ссылки"
    }
};