/* eslint-disable */
// This file is AUTO-GENERATED from config.yml by GitHub Action.
// Do NOT edit this file directly. Edit config.yml instead.

export const appConfig = {
    "dataUrl": "../data.json",
    "showLiveStreamSection": true,
    "showProfileSection": true,
    "showMinecraftSkinSection": true,
    "showLinksSection": true,
    "showYouTubeVideosSection": true,
    "showSupportButton": true,
    "supportUrl": "https://www.donationalerts.com/r/your_donate_page",
    "developmentMode": true
};

export const profileConfig = {
    "name": "Ваше Имя Здесь",
    "description": "Разработчик | Создатель Контента | Исследователь",
    "avatar": "./assets/avatar.png",
    "minecraftSkinUrl": "./assets/cool-guy-skin.png"
};

export const linksConfig = [
    {
        "label_key": "youtubeChannelLabel",
        "url": "https://www.youtube.com/channel/YOUR_YOUTUBE_CHANNEL_ID",
        "icon": "youtube",
        "order": 1,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "youtube",
        "subscribeUrl": "https://www.youtube.com/channel/YOUR_YOUTUBE_CHANNEL_ID?sub_confirmation=1",
        "active": true
    },
    {
        "label_key": "telegramChannelLabel",
        "url": "https://t.me/your_telegram_channel",
        "icon": "telegram",
        "order": 2,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "telegram",
        "active": true
    },
    {
        "label_key": "instagramProfileLabel",
        "url": "https://www.instagram.com/your_instagram_profile/",
        "icon": "instagram",
        "order": 3,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "instagram",
        "active": true
    },
    {
        "label_key": "xTwitterProfileLabel",
        "url": "https://x.com/your_x_profile",
        "icon": "x",
        "order": 4,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "x",
        "active": true
    },
    {
        "label_key": "twitchChannelLabel",
        "url": "https://www.twitch.tv/your_twitch_channel",
        "icon": "twitch",
        "order": 5,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "twitch",
        "active": true
    },
    {
        "label_key": "tiktokProfileLabel",
        "url": "https://www.tiktok.com/@your_tiktok_profile",
        "icon": "tiktok",
        "order": 6,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "tiktok",
        "active": true
    },
    {
        "label_key": "vkGroupLabel",
        "url": "https://vk.com/your_vk_group_id",
        "icon": "vk",
        "order": 7,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "vk_group",
        "active": true
    },
    {
        "label_key": "vkPersonalPageLabel",
        "url": "https://vk.com/idYOUR_VK_USER_ID",
        "icon": "vk",
        "order": 8,
        "isSocial": true,
        "showSubscriberCount": true,
        "platformId": "vk_personal",
        "active": true
    },
    {
        "label_key": "myPortfolioLabel",
        "url": "https://example.com/portfolio",
        "icon": "folderopen",
        "order": 9,
        "isSocial": false,
        "active": true
    },
    {
        "label_key": "hiddenLinkExample",
        "url": "https://example.com/hidden",
        "icon": "visibilityoff",
        "order": 10,
        "isSocial": false,
        "active": false
    }
];
